# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Luca Grella
logo:             /assets/img/logo.png
tagline:          'Welcome!'
description:      'Welcome to my Portfolio Website!'
url:              https://luca-grella.github.io
baseurl:          /
githublink:       https://github.com/luca-grella
instagram:        https://www.instagram.com/lucke94
twitter:          https://twitter.com/LucaTeckDj
facebook:         https://www.facebook.com/LucaTeckDj
spotify:          https://open.spotify.com/artist/7zD0ULnp6PqhVHqsfJFsIv
soundcloud:       https://soundcloud.com/djteck
linkedin:         https://www.linkedin.com/in/lucagrella/
google_scholar:   https://scholar.google.com/citations?user=TSDAR7sAAAAJ

author:
  name:           'Luca Grella'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
