# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Luca Grella
tagline:          'Prova'
description:      ' Prova <a href=" " target="_blank">Prova</a> Prova'
url:              https://luca-grella.github.io
baseurl:          /

author:
  name:           'Luca Grella'
  url:            https://www.linkedin.com/in/lucagrella

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luca-grella/luca-grella.github.io
  repo:           https://github.com/luca-grella
